ASCII Obfuscation: functions.c File Reference
functions.c File Reference
#include "functions.h"
#include "main.h"
#include <stdlib.h>
#include <iso646.h>
Functions
int randomize_value (char input, char *output, unsigned int *offset)
function implementation for ascii_obfuscation
int translate_into_obscure (char *input, unsigned int input_length, unsigned char *output, unsigned int *p_output_length)
Translation loop function.
Function Documentation
randomize_value()
int randomize_value (char input, char * output, unsigned int * offset)
function implementation for ascii_obfuscation
function definition for ascii_obfuscation
functions.c
Note
Created by vince on 08/02/2020.
Todo:
We have to revise the following lines to ensure they do what they are supposed to
Definition at line 43 of file functions.c.
References RETURN_OK.
Referenced by TEST_randomize_value(), and translate_into_obscure().
translate_into_obscure()
int translate_into_obscure (char * input, unsigned int input_length, unsigned char * output, unsigned int * p_output_length)
Translation loop function.
Translation loop function Parameters :
[in] input String that contains the original message
[in] input_length Length of input string
[out] output Buffer in which we would write the resulting string
[out] p_output_length Pointer to length of output string Return : An int value :
RETURN_OK (0) if everything is OK
GENERIC_ERROR (-1) if process ends in error
If 'output' buffer is 'NULL' we might get in trouble trying to set values to a random memory location
=> We would better exit the function as soon as possible with an error code to inform the caller
If there is no input buffer passed in argument, use default string 'message_str'
Definition at line 86 of file functions.c.
References GENERIC_ERROR, message_str, randomize_value(), and RETURN_OK.
Referenced by main(), and TEST_randomize_value().